# Generated by Django 3.1 on 2021-02-01 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20210201_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 14, 27, 13, 992316)),
        ),
    ]
