# Generated by Django 3.1 on 2021-02-06 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20210202_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='avatar',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 11, 47, 41, 885893), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(max_length=500),
        ),
    ]
