# Generated by Django 3.1 on 2021-02-06 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_auto_20210206_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 11, 50, 57, 271687), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=500),
        ),
    ]
