# Generated by Django 3.1 on 2021-02-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_auto_20210206_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
