# Generated by Django 3.1 on 2021-02-06 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_auto_20210206_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 6, 49, 54, 7616, tzinfo=utc), null=True),
        ),
    ]
