# Generated by Django 3.1 on 2021-02-06 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_auto_20210206_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postTimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
